# Generated by Django 3.0 on 2019-12-09 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('profissao', models.CharField(max_length=200)),
                ('ano_nasc', models.PositiveIntegerField()),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
